import {createRequire} from 'node:module';
import {mkdir,readFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {serve} from '../tools/serve.mjs';
import {fixture} from './fixture.mjs';
import {translations as previousTranslation} from '../content/translation-002.mjs';
const require = createRequire(import.meta.url);
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/jktru/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dist = fileURLToPath(new URL('../dist',import.meta.url));
const output = fileURLToPath(new URL('../tmp/qa',import.meta.url)); await mkdir(output,{recursive:true});
const actualBook=JSON.parse(await readFile(path.join(dist,'data/book.json'),'utf8'));
const priorBook=structuredClone(actualBook);priorBook.revision=2;
Object.assign(priorBook.chapters[1].sections[2],previousTranslation['ch01-s03']);
const server = serve(dist, async (url,res) => {
  if (url.pathname.startsWith('/prior/')) {
    url.pathname=url.pathname.slice('/prior'.length);
    if(url.pathname==='/data/book.js'){res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8'});res.end('window.STUDY_BOOK='+JSON.stringify(priorBook));return true;}
  }
  if (url.pathname.startsWith('/fixture/')) {
    url.pathname=url.pathname.slice('/fixture'.length);
    if(url.pathname==='/data/book.js'){res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8'});res.end('window.STUDY_BOOK='+JSON.stringify(fixture));return true;}
  }
  return false;
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin='http://127.0.0.1:'+server.address().port;
let browser;
try {
  browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
  const page=await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin); await page.locator('#sourceTitle').waitFor();
  assert.equal(await page.locator('#toc details').count(),29);
  assert.equal(await page.locator('#translatedMetric').innerText(),'151 раздел');
  assert.match(await page.locator('#sourceTitle').innerText(),/26 глав/);
  await page.screenshot({path:path.join(output,'home-desktop.png'),fullPage:true});
  await page.click('#notesButton'); await page.fill('#personalNotes','Общая заметка: проверить источник.'); await page.click('[data-close="notesDialog"]');
  await page.reload(); await page.click('#notesButton'); assert.equal(await page.inputValue('#personalNotes'),'Общая заметка: проверить источник.'); await page.click('[data-close="notesDialog"]');
  await page.setViewportSize({width:390,height:844}); await page.screenshot({path:path.join(output,'home-mobile.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.click('#tocButton'); assert(await page.locator('#sidebar').isVisible()); await page.click('#closeToc');
  await page.goto(origin+'/#section=ch01-s02');await page.locator('#sectionTitle').waitFor();
  assert.equal(await page.locator('#sectionTitle').innerText(),'Общие вопросы');
  assert.equal(await page.locator('#article h2').count(),2);
  assert.equal(await page.locator('#article h3').count(),10);
  assert.match(await page.locator('#article').innerText(),/галлюцинации.*могут возникать у здоровых/s);
  assert.match(await page.locator('#editorNotes').innerText(),/не текст книги/);
  assert.match(await page.locator('#sourceReference').innerText(),/11–13.*2–4/);
  await page.click('#sectionOutline summary');await page.getByRole('button',{name:'Форма и содержание',exact:true}).click();assert(await page.evaluate(()=>window.scrollY>400));
  await page.click('#notesButton');assert.equal(await page.locator('#summary li').count(),7);await page.click('[data-close="notesDialog"]');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.setViewportSize({width:1365,height:1000});await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:path.join(output,'actual-general-issues.png')});
  await page.goto(origin+'/prior/index.html#section=ch01-s03');await page.locator('#partialNotice').waitFor();
  assert.match(await page.locator('#sectionStatus').innerText(),/частично/);
  assert.match(await page.locator('#partialNotice').innerText(),/13–17.*4–8/s);
  assert.match(await page.locator('#continuationNotice').innerText(),/Disturbances of thoughts/);
  assert.equal(await page.locator('#article .box').count(),1);
  assert.equal(await page.locator('#article .box li').count(),14);
  assert.equal(await page.locator('#article h2').count(),2);
  await page.screenshot({path:path.join(output,'actual-emotions-perception.png')});
  await page.click('#completeButton');assert.match(await page.locator('#completeButton').innerText(),/Часть прочитана/);assert.match(await page.locator('#readCount').innerText(),/^0 из 267/);assert.match(await page.locator('#readHint').innerText(),/доступные части: 1/);
  await page.click('#notesButton');assert.equal(await page.locator('#summary li').count(),10);assert.match(await page.locator('#summary').innerText(),/только к переведённой части/);
  await page.fill('#personalNotes','Проверить определения иллюзии и галлюцинации.');
  const partialDownload=page.waitForEvent('download');await page.click('#exportNotes');const partialMD=await partialDownload;assert.match(await readFile(await partialMD.path(),'utf8'),/Переведённая часть: PDF 13–17/);
  await page.click('[data-close="notesDialog"]');await page.reload();assert.match(await page.locator('#completeButton').innerText(),/Часть прочитана/);
  await page.click('#notesButton');assert.equal(await page.inputValue('#personalNotes'),'Проверить определения иллюзии и галлюцинации.');await page.click('[data-close="notesDialog"]');
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(output,'actual-partial-mobile.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.locator('#article .box').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:path.join(output,'actual-box-mobile.png')});
  await page.goto(origin+'/#section=ch01-s03');await page.locator('#sectionTitle').waitFor();
  assert(await page.locator('#partialNotice').isHidden());assert(await page.locator('#continuationNotice').isHidden());
  assert.equal(await page.locator('#article .box').count(),5);assert.match(await page.locator('#article').innerText(),/Landi et al\. \(2016\)/);
  assert.match(await page.locator('#readCount').innerText(),/^0 из 267/);assert.equal(await page.locator('#completeButton').innerText(),'Отметить прочитанным');
  await page.click('#notesButton');assert.equal(await page.inputValue('#personalNotes'),'Проверить определения иллюзии и галлюцинации.');assert.equal(await page.locator('#summary li').count(),21);await page.click('[data-close="notesDialog"]');
  await page.click('#completeButton');assert.match(await page.locator('#readCount').innerText(),/^1 из 267/);
  await page.goto(origin+'/#section=ch02-s07');await page.locator('table').first().waitFor();assert.equal(await page.locator('table').count(),3);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.locator('table').first().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'classification-tables-mobile.png')});
  await page.goto(origin+'/#section=ch03-s04');await page.locator('#sectionTitle').waitFor();assert.match(await page.locator('#article').innerText(),/кататон|Кататон/);
  await page.setViewportSize({width:1365,height:1000});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(output,'mental-state-desktop.png')});
  await page.goto(origin+'/#section=ch03-s11');await page.locator('#sectionTitle').waitFor();assert.match(await page.locator('#sectionStatus').innerText(),/Сверено/);assert(!(await page.locator('#completeButton').isDisabled()));
  await page.click('#nextButton');await page.waitForFunction(()=>location.hash==='#section=ch04-s01');assert(!(await page.locator('#completeButton').isDisabled()));
  await page.goto(origin+'/#section=ch04-s04');await page.locator('table').waitFor();assert.equal(await page.locator('table tbody tr').count(),11);
  await page.goto(origin+'/#section=ch15-s15');await page.locator('#sectionTitle').waitFor();await page.click('#nextButton');await page.waitForFunction(()=>location.hash==='#section=ch16-s01'&&document.getElementById('completeButton').disabled);assert(await page.locator('#completeButton').isDisabled());
  await page.goto(origin+'/#section=ch06-s03');await page.locator('#article img').first().waitFor({state:'attached'});assert.equal(await page.locator('#article img').count(),2);for(const img of await page.locator('#article img').all()){await img.locator('..').scrollIntoViewIfNeeded();await img.evaluate(i=>i.decode());assert(await img.evaluate(i=>i.naturalWidth>0));}
  await page.goto(origin+'/#section=ch10-s10');await page.locator('table').waitFor();assert.equal(await page.locator('table tbody tr').count(),8);assert.match(await page.locator('#article').innerText(),/0,65–2,47/);
  await page.goto(origin+'/#section=ch10-s12');await page.locator('#article img').waitFor({state:'attached'});assert.equal(await page.locator('#article .box').count(),4);await page.locator('#article img').scrollIntoViewIfNeeded();await page.locator('#article img').evaluate(i=>i.decode());await page.screenshot({path:path.join(output,'bipolar-figure-desktop.png')});
  await page.setViewportSize({width:390,height:844});await page.locator('#article img').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.join(output,'bipolar-figure-mobile.png')});await page.click('#notesButton');assert.equal(await page.locator('#summary li').count(),4);await page.fill('#personalNotes','Глава 10: сверить ранние признаки рецидива.');await page.click('[data-close="notesDialog"]');await page.reload();await page.click('#notesButton');assert.equal(await page.inputValue('#personalNotes'),'Глава 10: сверить ранние признаки рецидива.');await page.click('[data-close="notesDialog"]');
  await page.goto(origin+'/#section=ch11-s05');await page.locator('#article img').waitFor({state:'attached'});await page.locator('#article img').scrollIntoViewIfNeeded();await page.locator('#article img').evaluate(i=>i.decode());assert(await page.locator('#article img').evaluate(i=>i.naturalWidth>0));await page.screenshot({path:path.join(output,'schizophrenia-figure-mobile.png')});
  await page.goto(origin+'/#section=ch12-s04');await page.locator('table').waitFor();assert.equal(await page.locator('table tbody tr').count(),6);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.join(output,'delusional-types-mobile.png')});
  await page.goto(origin+'/#section=ch12-s06');await page.locator('#sectionTitle').waitFor();assert.match(await page.locator('#article').innerText(),/Интерметаморфоз/);await page.click('#notesButton');assert.equal(await page.locator('#summary li').count(),5);await page.fill('#personalNotes','Глава 12: отличать бред от сверхценной идеи.');await page.click('[data-close="notesDialog"]');await page.reload();await page.click('#notesButton');assert.equal(await page.inputValue('#personalNotes'),'Глава 12: отличать бред от сверхценной идеи.');await page.click('[data-close="notesDialog"]');
  await page.goto(origin+'/#section=ch13-s02');await page.locator('#article img').waitFor({state:'attached'});await page.locator('#article img').scrollIntoViewIfNeeded();await page.locator('#article img').evaluate(i=>i.decode());assert(await page.locator('#article img').evaluate(i=>i.naturalWidth>0));
  await page.goto(origin+'/#section=ch14-s07');await page.locator('table').first().waitFor();assert.equal(await page.locator('#article .box').count(),14);assert.equal(await page.locator('table').count(),3);
  await page.goto(origin+'/#section=ch15-s07');await page.locator('table').waitFor();assert.equal(await page.locator('#article .box').count(),8);assert.equal(await page.locator('table tbody tr').count(),11);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.locator('table').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'personality-criteria-mobile.png')});
  await page.goto(origin+'/#section=ch15-s13');await page.locator('#sectionTitle').waitFor();assert.equal(await page.locator('#article .box').count(),2);await page.click('#notesButton');assert.equal(await page.locator('#summary li').count(),6);await page.fill('#personalNotes','Глава 15: различать симптоматические и функциональные исходы.');await page.click('[data-close="notesDialog"]');await page.reload();await page.click('#notesButton');assert.equal(await page.inputValue('#personalNotes'),'Глава 15: различать симптоматические и функциональные исходы.');await page.click('[data-close="notesDialog"]');
  await page.goto(origin+'/#section=index-main');await page.locator('#sectionTitle').waitFor();assert(await page.locator('#nextButton').isDisabled());
  await page.goto(origin+'/#section=ch25-s09');await page.locator('#sectionTitle').waitFor();assert.equal(await page.locator('#sectionTitle').innerText(),'Антидепрессанты');assert(await page.locator('#completeButton').isDisabled());
  await context.close();
  const ctx=await browser.newContext({viewport:{width:1365,height:1000},acceptDownloads:true});
  await ctx.addInitScript(()=>{
    localStorage.setItem('psychiatry-auto-next','0');
    let active; const voice={name:'Тестовый русский голос',lang:'ru-RU',voiceURI:'test-ru',localService:true};
    window.fakeSpeech={cancelled:0,paused:0,resumed:0,spoken:[],getVoices:()=>[voice],addEventListener:()=>{},cancel(){this.cancelled++;active=null;},pause(){this.paused++;},resume(){this.resumed++;},speak(u){active=u;this.spoken.push(u.text);},finish(){active?.onend?.();}};
    Object.defineProperty(window,'speechSynthesis',{value:window.fakeSpeech,configurable:true});
    Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class { constructor(text){this.text=text;} },configurable:true});
  });
  const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));
  await p.goto(origin+'/#section=ch01-s03');await p.locator('#sectionTitle').waitFor();await p.click('#speakButton');
  await p.evaluate(()=>{for(let n=0;n<1000 && !document.getElementById('stopButton').disabled;n++)fakeSpeech.finish();});
  assert.match(await p.locator('#speechStatus').innerText(),/Раздел озвучен/);
  const spoken=await p.evaluate(()=>fakeSpeech.spoken.join(' '));assert.match(spoken,/Вставка 1.1/);assert.match(spoken,/Вставка 1.5/);assert.match(spoken,/Landi et al\. \(2016\)/);assert(!spoken.includes('Это пояснение переводчика'));assert(!spoken.includes('Продолжение ещё не добавлено'));
  await p.goto(origin+'/fixture/index.html#section=test-first');
  await p.locator('#sectionTitle').waitFor();assert.equal(await p.locator('#sectionTitle').innerText(),'Первый тестовый раздел');
  assert.equal(await p.locator('#article img').count(),0);assert.match(await p.locator('#article').innerText(),/<img src=x/);
  assert.equal(await p.locator('table tbody td').count(),2);assert(await p.locator('#previousButton').isDisabled());
  await p.click('#speakButton');assert.equal(await p.evaluate(()=>fakeSpeech.spoken.length),1);await p.click('#speakButton');assert.equal(await p.evaluate(()=>fakeSpeech.paused),1);await p.click('#speakButton');assert.equal(await p.evaluate(()=>fakeSpeech.resumed),1);
  await p.evaluate(()=>fakeSpeech.finish());assert.equal(await p.evaluate(()=>fakeSpeech.spoken.length),2);await p.click('#stopButton');assert(await p.locator('#stopButton').isDisabled());
  await p.click('#completeButton');assert.match(await p.locator('#readCount').innerText(),/^1 из 3/);
  await p.click('#notesButton');await p.fill('#personalNotes','Заметка к первому разделу');
  const exported=p.waitForEvent('download');await p.click('#exportNotes');const md=await exported;assert.match(await readFile(await md.path(),'utf8'),/Заметка к первому разделу/);
  const backupEvent=p.waitForEvent('download');await p.click('#backupInNotes');const backup=await backupEvent;const copy=await readFile(await backup.path(),'utf8');assert.equal(JSON.parse(copy).notes['test-first'],'Заметка к первому разделу');
  await p.click('[data-close="notesDialog"]');await p.reload();await p.click('#notesButton');assert.equal(await p.inputValue('#personalNotes'),'Заметка к первому разделу');await p.click('[data-close="notesDialog"]');
  await p.screenshot({path:path.join(output,'reader-desktop-test-only.png'),fullPage:true});
  await p.click('#speakButton');await p.click('#nextButton');await p.waitForFunction(()=>location.hash.includes('test-pending'));assert(await p.locator('#speakButton').isDisabled());assert(await p.locator('#completeButton').isDisabled());assert.equal(await p.locator('.speaking').count(),0);
  await p.click('#notesButton');assert.equal(await p.inputValue('#personalNotes'),'');await p.fill('#personalNotes','Вопрос к следующему разделу');await p.click('[data-close="notesDialog"]');
  await p.click('#nextButton');await p.locator('#draftWarning').waitFor();assert(await p.locator('#nextButton').isDisabled());assert(await p.locator('#completeButton').isDisabled());
  await p.fill('#search','Первый');assert.equal(await p.locator('.toc-item').count(),1);await p.click('.toc-item');
  await p.click('#libraryButton');
  const bad={...fixture,revision:2,source:{...fixture.source,sha256:'b'.repeat(64)}};
  await p.locator('#packageInput').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await p.waitForFunction(()=>document.getElementById('libraryStatus').textContent.includes('отличается'));
  const fresh=structuredClone(fixture);fresh.revision=2;fresh.chapters[0].sections[0].revision=2;fresh.chapters[0].sections[0].blocks[0].text='Новая версия тестового текста.';
  await p.locator('#packageInput').setInputFiles({name:'new.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fresh))});await p.waitForFunction(()=>document.getElementById('libraryStatus').textContent.includes('Новая версия добавлена'));
  await p.click('[data-close="libraryDialog"]');assert.match(await p.locator('#readCount').innerText(),/^0 из 3/);await p.click('#notesButton');assert.equal(await p.inputValue('#personalNotes'),'Заметка к первому разделу');await p.click('[data-close="notesDialog"]');
  await p.reload();assert.match(await p.locator('#article').innerText(),/Новая версия/);
  await p.click('#libraryButton');p.once('dialog',d=>d.accept());await p.locator('#backupInput').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(copy)});await p.waitForFunction(()=>document.getElementById('libraryStatus').textContent.includes('восстановлены'));
  await p.click('[data-close="libraryDialog"]');await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await p.screenshot({path:path.join(output,'reader-mobile-test-only.png'),fullPage:true});
  assert.deepEqual(errors,[]);console.log('PASS: actual PDF-linked content, partial reading boundaries and progress, responsive layouts, notes persistence, safe rendering, speech controls/cancel, source validation, exports, backup restore and package update.');
} catch(error) {console.error(error);throw error;} finally {await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}

